#默认使用配置
spring:
  profiles:
    active: dev
#  thymeleaf:
#    #清除缓存，实现热部署。也就是修改了html后不用重启(提前引入thymeleaf依赖)(PS: 修改完html后一定要ctrl+f9重新build一下。再回到浏览器刷新)
#    cache: false
#    #回避HTML进行严格的检查的配置(提前引入nekohtml依赖)
#    mode: LEGACYHTML5
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      # =classpath目录下的templates文件夹内容修改不重启
      exclude: templates/**


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  #扫描实例类的所在包
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapping/*Mapper.xml

#mybatis plus
mybatis-plus:
  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  mapper-locations: classpath*:/mapping/**Mapper.xml
  #指明实体扫描(多个package用逗号或者分号分隔)
  typeAliasesPackage: com.example.demo.**.entity
  global-config:
    #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
    id-type: 0
    #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
    field-strategy: 2
    #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
    db-column-underline: true
    #是否动态刷新mapper
    refresh-mapper: true # 刷新mapper 调试神器






