#开发配置
server:
  port: 8090

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/zeroone?serverTimezone=GMT%2B8
    username: zeroone
    password: zeroone
#    password: hj123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


Frame:
  file:
    save-file-path: D:\test\