#默认使用配置
spring:
  profiles:
    active: dev


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  #扫描实力类的所在包
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapping/*Mapper.xml



